// Nursery rhymes for sing-along mode.
// Each song has a REAL sung recording (audio) sourced from Wikimedia Commons,
// converted to mp3 and self-hosted under /public/songs. `credit` carries the
// attribution required by the file's licence (see the in-app credits screen).
export const NURSERY_RHYMES = [
  {
    id: 'twinkle',
    title: 'Twinkle Twinkle Little Star',
    emoji: '⭐',
    audio: '/songs/twinkle.mp3',
    duration: 24.6,
    credit: { author: 'CommandSpry', license: 'CC BY-SA 3.0', source: 'https://commons.wikimedia.org/wiki/File:Twinkle_twinkle_little_star_(vocal).ogg' },
    lines: [
      'Twinkle twinkle little star',
      'How I wonder what you are',
      'Up above the world so high',
      'Like a diamond in the sky',
      'Twinkle twinkle little star',
      'How I wonder what you are',
    ],
  },
  {
    id: 'baa-baa',
    title: 'Baa Baa Black Sheep',
    emoji: '🐑',
    audio: '/songs/baa-baa.mp3',
    duration: 24.0,
    credit: { author: 'CambridgeBayWeather', license: 'CC BY-SA 3.0', source: 'https://commons.wikimedia.org/wiki/File:Baa,_Baa,_Blacksheep.ogg' },
    lines: [
      'Baa baa black sheep have you any wool',
      'Yes sir yes sir three bags full',
      'One for the master and one for the dame',
      'And one for the little boy who lives down the lane',
    ],
  },
  {
    id: 'old-macdonald',
    title: 'Old MacDonald Had a Farm',
    emoji: '🐄',
    audio: '/songs/old-macdonald.mp3',
    duration: 31.9,
    credit: { author: 'CambridgeBayWeather', license: 'CC BY-SA 3.0', source: 'https://commons.wikimedia.org/wiki/File:Old_McDonald_Had_a_Farm.ogg' },
    lines: [
      'Old MacDonald had a farm E I E I O',
      'And on his farm he had a cow E I E I O',
      'With a moo moo here and a moo moo there',
      'Here a moo there a moo everywhere a moo moo',
      'Old MacDonald had a farm E I E I O',
    ],
  },
  {
    id: 'row-row',
    title: 'Row Row Row Your Boat',
    emoji: '🚣',
    audio: '/songs/row-row.mp3',
    duration: 7.9,
    credit: { author: 'CambridgeBayWeather', license: 'CC BY-SA 3.0', source: 'https://commons.wikimedia.org/wiki/File:Row,_Row,_Row_Your_Boat.ogg' },
    lines: [
      'Row row row your boat',
      'Gently down the stream',
      'Merrily merrily merrily merrily',
      'Life is but a dream',
    ],
  },
  {
    id: 'itsy-bitsy',
    title: 'Itsy Bitsy Spider',
    emoji: '🕷️',
    audio: '/songs/itsy-bitsy.mp3',
    duration: 18.5,
    credit: { author: 'Wwaters', license: 'CC BY-SA 3.0', source: 'https://commons.wikimedia.org/wiki/File:Itsy_Bitsy_Spider.ogg' },
    lines: [
      'The itsy bitsy spider went up the water spout',
      'Down came the rain and washed the spider out',
      'Out came the sun and dried up all the rain',
      'And the itsy bitsy spider went up the spout again',
    ],
  },
  {
    id: 'mary-lamb',
    title: 'Mary Had a Little Lamb',
    emoji: '🐏',
    audio: '/songs/mary-lamb.mp3',
    duration: 22.8,
    credit: { author: 'Celestianpower', license: 'Public domain', source: 'https://commons.wikimedia.org/wiki/File:Mary_Had_a_Little_Lamb.ogg' },
    lines: [
      'Mary had a little lamb',
      'Its fleece was white as snow',
      'And everywhere that Mary went',
      'The lamb was sure to go',
    ],
  },
  {
    id: 'jack-and-jill',
    title: 'Jack and Jill',
    emoji: '⛰️',
    audio: '/songs/jack-and-jill.mp3',
    duration: 19.0,
    credit: { author: 'Unknown (1890)', license: 'Public domain', source: 'https://commons.wikimedia.org/wiki/File:Jack_and_Jill_(1890).ogg' },
    lines: [
      'Jack and Jill went up the hill',
      'To fetch a pail of water',
      'Jack fell down and broke his crown',
      'And Jill came tumbling after',
    ],
  },
  {
    id: 'abc',
    title: 'The Alphabet Song',
    emoji: '🔤',
    audio: '/songs/abc.mp3',
    duration: 23.9,
    credit: { author: 'CambridgeBayWeather', license: 'CC BY-SA 3.0', source: 'https://commons.wikimedia.org/wiki/File:Alphabet_song.ogg' },
    lines: [
      'A B C D E F G',
      'H I J K L M N O P',
      'Q R S T U and V',
      'W X Y and Z',
      'Now I know my ABCs',
      'Next time won\'t you sing with me',
    ],
  },
]
