// Nursery rhymes for sing-along mode. Each song has a REAL sung recording
// (audio) self-hosted under /public/songs. `credit` carries attribution.
//
// mary-lamb is the one survivor of the original Wikimedia Commons batch —
// the rest turned out to be piano-only or poor quality on actual listen (see
// git history). The rest below are from a royalty-free pack the user
// confirmed the licence on, with lyrics transcribed from the pack's own
// Lyrics.md. muffin-man, pat-a-cake and yankee-doodle weren't in that file;
// their lines below are the standard traditional lyrics for these public-
// domain rhymes rather than a transcription of this exact recording.
//
// leadIn/outro (seconds) mark where singing actually starts/ends within the
// audio file, measured via ffmpeg silencedetect against the real recordings —
// the karaoke highlight in SingAlong.jsx maps word progress across that
// window instead of the full file, so it doesn't drift during lead-in music
// or a trailing instrumental outro.
const PACK_CREDIT = { author: 'FreeSongPackage', license: 'Royalty-free', source: '' }

export const NURSERY_RHYMES = [
  {
    id: 'mary-lamb',
    title: 'Mary Had a Little Lamb',
    emoji: '🐏',
    audio: '/songs/mary-lamb.mp3',
    duration: 22.8,
    leadIn: 0,
    outro: 22.8,
    credit: { author: 'Celestianpower', license: 'Public domain', source: 'https://commons.wikimedia.org/wiki/File:Mary_Had_a_Little_Lamb.ogg' },
    lines: [
      'Mary had a little lamb',
      'Its fleece was white as snow',
      'And everywhere that Mary went',
      'The lamb was sure to go',
    ],
  },
  { id: 'abc', title: 'The Alphabet Song', emoji: '🔤', audio: '/songs/abc.mp3', duration: 50.3, leadIn: 0.98, outro: 43.49, credit: PACK_CREDIT, lines: [
      'A - B - C - D - E - F - G',
      'H - I - J - K - L - M - N - O - P',
      'Q - R - S - T - U- V,',
      'W - X - Y and Z',
      'Now I know my ABC\'s',
      'Next time won\'t you sing with me.',
    ] },
  { id: 'baa-baa', title: 'Baa Baa Black Sheep', emoji: '🐑', audio: '/songs/baa-baa.mp3', duration: 81.5, leadIn: 1.12, outro: 79.69, credit: PACK_CREDIT, lines: [
      'Baa, baa, black sheep, have you any wool?',
      'Yes sir, yes sir, three bags full!',
      'One for the master,',
      'One for the dame,',
      'And one for the little boy Who lives down the lane',
    ] },
  { id: 'bingo', title: 'Bingo', emoji: '🐶', audio: '/songs/bingo.mp3', duration: 96.2, leadIn: 0.61, outro: 94.51, credit: PACK_CREDIT, lines: [
      'There was a farmer who had a dog,',
      'And Bingo was his name-o.',
      'B-I-N-G-O',
      'B-I-N-G-O',
      'B-I-N-G-O',
      'And Bingo was his name-o.',
      'There was a farmer who had a dog,',
      'And Bingo was his name-o.',
      '(clap)-I-N-G-O',
      '(clap)-I-N-G-O',
      '(clap)-I-N-G-O',
      'And Bingo was his name-o.',
      'There was a farmer who had a dog,',
      'And Bingo was his name-o.',
      '(clap)-(clap)-N-G-O',
      '(clap)-(clap)-N-G-O',
      '(clap)-(clap)-N-G-O',
      'And Bingo was his name-o.',
      'There was a farmer who had a dog,',
      'And Bingo was his name-o.',
      '(clap)-(clap)-(clap)-G-O',
      '(clap)-(clap)-(clap)-G-O',
      '(clap)-(clap)-(clap)-G-O',
      'And Bingo was his name-o.',
      'There was a farmer who had a dog,',
      'And Bingo was his name-o.',
      '(clap)-(clap)-(clap)-(clap)-O',
      '(clap)-(clap)-(clap)-(clap)-O',
      '(clap)-(clap)-(clap)-(clap)-O',
      'And Bingo was his name-o.',
      'There was a farmer who had a dog,',
      'And Bingo was his name-o.',
      '(clap)-(clap)-(clap)-(clap)-(clap)',
      '(clap)-(clap)-(clap)-(clap)-(clap)',
      '(clap)-(clap)-(clap)-(clap)-(clap)',
      'And Bingo was his name-o.',
    ] },
  { id: 'brother-john', title: 'Are You Sleeping (Brother John)', emoji: '🔔', audio: '/songs/brother-john.mp3', duration: 86.9, leadIn: 1.33, outro: 83.44, credit: PACK_CREDIT, lines: [
      'Are you sleeping, are you sleeping?',
      'Brother John, Brother John?',
      'Morning bells are ringing, morning bells are ringing',
      'Ding ding dong, ding ding dong.',
    ] },
  { id: 'clap-your-hands', title: 'Clap Clap Clap Your Hands', emoji: '👏', audio: '/songs/clap-your-hands.mp3', duration: 82.0, leadIn: 0.92, outro: 75.77, credit: PACK_CREDIT, lines: [
      'Clap, clap, clap your hands',
      'Clap your hands together',
      'Clap, clap, clap your hands',
      'Clap your hands together',
      'Shake, shake, shake your hands',
      'Shake your hands together',
      'Shake, shake, shake your hands',
      'Shake your hands together',
      'Pound, pound, pound your hands',
      'Pound your hands together',
      'Pound, pound, pound your hands',
      'Pound your hands together',
      'Roll, roll, roll your hands',
      'Roll your hands together',
      'Roll, roll, roll your hands',
      'Roll your hands together',
      'Pat, pat, pat your face',
      'Pat your face together',
      'Pat, pat, pat your face',
      'Pat your face together',
    ] },
  { id: 'finger-family', title: 'Finger Family', emoji: '✋', audio: '/songs/finger-family.mp3', duration: 63.6, leadIn: 1.37, outro: 62.3, credit: PACK_CREDIT, lines: [
      'Daddy finger, daddy finger, where are you?',
      'Here I am, here I am',
      'How do you do?',
      'Mommy finger, mommy finger, where are you?',
      'Here I am, here I am',
      'How do you do?',
      'Brother finger, brother finger, where are you?',
      'Here I am, here I am',
      'How do you do?',
      'Sister finger, sister finger, where are you?',
      'Here I am, here I am',
      'How do you do?',
      'Baby finger, baby finger, where are you?',
      'Here I am, here I am',
      'How do you do?',
    ] },
  { id: 'five-little-monkeys', title: 'Five Little Monkeys', emoji: '🐒', audio: '/songs/five-little-monkeys.mp3', duration: 122.3, leadIn: 0.89, outro: 116.97, credit: PACK_CREDIT, lines: [
      'Five little monkeys jumping on the bed',
      'One fell off and bumped his head',
      'Mama called the doctor,',
      'And the doctor said',
      'No more monkeys jumping on the bed',
      'Four little monkeys jumping on the bed',
      'One fell off and bumped his head',
      'Mama called the doctor',
      'And the doctor said,',
      'No more monkeys jumping on the bed',
      'Three little monkeys jumping on the bed',
      'One fell off and bumped his head',
      'Mama called the doctor',
      'And the doctor said,',
      'No more monkeys jumping on the bed',
      'Two little monkeys jumping on the bed',
      'One fell off and bumped his head',
      'Mama called the doctor',
      'And the doctor said,',
      'No more monkeys jumping on the bed',
      'One little monkey jumping on the bed',
      'One fell off and bumped his head',
      'Mama called the doctor',
      'And the doctor said,',
      'Put those monkeys right to bed',
    ] },
  { id: 'happy-birthday', title: 'Happy Birthday', emoji: '🎂', audio: '/songs/happy-birthday.mp3', duration: 172.8, leadIn: 0.51, outro: 172.75, credit: PACK_CREDIT, lines: [
      'Happy Birthday to You',
      'Happy Birthday to You',
      'Happy Birthday Happy Birthday',
      'Happy Birthday to You',
    ] },
  { id: 'head-shoulders-knees-toes', title: 'Head, Shoulders, Knees and Toes', emoji: '🕺', audio: '/songs/head-shoulders-knees-toes.mp3', duration: 121.7, leadIn: 0.0, outro: 113.68, credit: PACK_CREDIT, lines: [
      'Head and shoulders knees and toes',
      'Knees and toes',
      'Head and shoulders knees and toes',
      'Knees and toes',
      'And eyes and ears',
      'And mouth and nose',
      'Head and shoulders knees and toes',
      'Knees and toes',
    ] },
  { id: 'hickory-dickory-dock', title: 'Hickory Dickory Dock', emoji: '🕰️', audio: '/songs/hickory-dickory-dock.mp3', duration: 74.8, leadIn: 0.55, outro: 72.81, credit: PACK_CREDIT, lines: [
      'Hickory dickory dock,',
      'The mouse ran up the clock.',
      'The clock struck one,',
      'The mouse ran down,',
      'Hickory dickory dock.',
    ] },
  { id: 'hush-little-baby', title: 'Hush Little Baby', emoji: '🌙', audio: '/songs/hush-little-baby.mp3', duration: 73.2, leadIn: 0.78, outro: 71.59, credit: PACK_CREDIT, lines: [
      'Hush, little baby, don\'t say a word.',
      'Papa\'s gonna buy you a mockingbird',
      'And if that mockingbird won\'t sing,',
      'Papa\'s gonna buy you a diamond ring',
      'And if that diamond ring turns brass,',
      'Papa\'s gonna buy you a looking glass',
      'And if that looking glass gets broke,',
      'Papa\'s gonna buy you a billy goat',
      'And if that billy goat won\'t pull,',
      'Papa\'s gonna buy you a cart and bull',
      'And if that cart and bull turn over,',
      'Papa\'s gonna buy you a dog named Rover',
      'And if that dog named Rover won\'t bark',
      'Papa\'s gonna buy you a horse and cart',
      'And if that horse and cart fall down,',
      'You\'ll still be the sweetest little baby in town.',
    ] },
  { id: 'if-youre-happy', title: "If You're Happy and You Know It", emoji: '😃', audio: '/songs/if-youre-happy.mp3', duration: 94.8, leadIn: 0.39, outro: 93.39, credit: PACK_CREDIT, lines: [
      'If you\'re happy and you know it, clap your hands (clap clap)',
      'If you\'re happy and you know it, clap your hands (clap clap)',
      'If you\'re happy and you know it, and you really wanna show it',
      'If you\'re happy and you know it, clap your hands. (clap clap)',
      'If you\'re happy and you know it, stomp your feet (stomp stomp)',
      'If you\'re happy and you know it, stomp your feet (stomp stomp)',
      'If you\'re happy and you know it, and you really wanna show it',
      'If you\'re happy and you know it, stomp your feet. (stomp stomp)',
      'If you\'re happy and you know it, snap your fingers (snap snap)',
      'If you\'re happy and you know it, snap your fingers(snap snap)',
      'If you\'re happy and you know it, and you really wanna show it',
      'If you\'re happy and you know it, snap your fingers (snap snap)',
      'If you\'re happy and you know it, shout "Hurray!" (hoo-ray!)',
      'If you\'re happy and you know it, shout "Hurray!" (hoo-ray!)',
      'If you\'re happy and you know it, and you really wanna show it',
      'If you\'re happy and you know it, shout "Hurray!" (hoo-ray!)',
      'If you\'re happy and you know it, clap your hands (clap clap)',
      'If you\'re happy and you know it, clap your hands (clap clap)',
      'If you\'re happy and you know it, and you really wanna show it',
      'If you\'re happy and you know it, clap your hands. (clap clap)',
      'If you\'re happy and you know it, and you really wanna show it',
      'If you\'re happy and you know it, clap your hands. (clap clap)',
    ] },
  { id: 'im-a-little-star', title: "I'm a Little Star", emoji: '⭐', audio: '/songs/im-a-little-star.mp3', duration: 78.1, leadIn: 0.72, outro: 75.83, credit: PACK_CREDIT, lines: [
      'I\'m a little star, hanging on a tree.',
      'See the little children dance around me.',
      'Tra-la-la, tra-la-la',
      'Tra-la-la, la-la-la',
      'Tra-la-la, tra-la-la',
      'Tra-la-la, la',
      'I\'m a candy stick, hanging on a tree.',
      'See the little children dance around me.',
      'I\'m a pretty angel, hanging on a tree.',
      'See the little children dance around me.',
      'I\'m a bright light, hanging on a tree.',
      'See the little children dance around me.',
    ] },
  { id: 'im-a-little-teapot', title: "I'm a Little Teapot", emoji: '🫖', audio: '/songs/im-a-little-teapot.mp3', duration: 22.2, leadIn: 0.35, outro: 20.47, credit: PACK_CREDIT, lines: [
      'I\'m a little teapot',
      'Short and stouts',
      'Here is my handle',
      'Here is my spout',
      'When I get all steamed up',
      'Hear me shout',
      'Just tip me over and pour me out',
    ] },
  { id: 'little-snowflake', title: 'Little Snowflake', emoji: '❄️', audio: '/songs/little-snowflake.mp3', duration: 132.8, leadIn: 0.83, outro: 131.36, credit: PACK_CREDIT, lines: [
      'Snowflake, snowflake, little snowflake.',
      'Little snowflake falling from the sky.',
      'Snowflake, snowflake, little snowflake.',
      'Falling, falling, falling, falling, falling,',
      'falling, falling, falling, falling…',
      'falling on my head.',
      'Snowflake, snowflake, little snowflake.',
      'Little snowflake falling from the sky.',
      'Snowflake, snowflake, little snowflake.',
      'Falling, falling, falling, falling, falling,',
      'falling, falling, falling, falling…',
      'falling on my nose.',
      'Snowflake, snowflake, little snowflake.',
      'Little snowflake falling from the sky.',
      'Snowflake, snowflake, little snowflake.',
      'Falling, falling, falling, falling, falling,',
      'falling, falling, falling, falling…',
      'falling in my hand.',
      'Falling on my head.',
      'Falling on my nose.',
      'Falling in my hand.',
      'Snowflake, snowflake, little snowflake…',
    ] },
  { id: 'london-bridge', title: 'London Bridge Is Falling Down', emoji: '🌉', audio: '/songs/london-bridge.mp3', duration: 85.7, leadIn: 0.45, outro: 84.35, credit: PACK_CREDIT, lines: [
      'London Bridge is falling down,',
      'Falling down, falling down.',
      'London Bridge is falling down,',
      'My fair lady.',
      'Build it up with wood and clay,',
      'Wood and clay, wood and clay,',
      'Build it up with wood and clay,',
      'My fair lady.',
      'Wood and clay will wash away,',
      'Wash away, wash away,',
      'Wood and clay will wash away,',
      'My fair lady.',
      'Build it up with bricks and mortar,',
      'Bricks and mortar, bricks and mortar,',
      'Build it up with bricks and mortar,',
      'My fair lady.',
      'Bricks and mortar will not stay,',
      'Will not stay, will not stay,',
      'Bricks and mortar will not stay,',
      'My fair lady.',
      'Build it up with silver and gold,',
      'Silver and gold, silver and gold,',
      'Build it up with silver and gold,',
      'My fair lady.',
    ] },
  { id: 'muffin-man', title: 'The Muffin Man', emoji: '🧁', audio: '/songs/muffin-man.mp3', duration: 108.2, leadIn: 0.0, outro: 106.6, credit: PACK_CREDIT, lines: [
      'Oh, do you know the muffin man,',
      'The muffin man, the muffin man?',
      'Oh, do you know the muffin man,',
      'Who lives on Drury Lane?',
      'Oh, yes, I know the muffin man,',
      'The muffin man, the muffin man,',
      'Oh, yes, I know the muffin man,',
      'Who lives on Drury Lane.',
      'Oh, do you know the muffin man,',
      'The muffin man, the muffin man?',
      'Oh, do you know the muffin man,',
      'Who lives on Drury Lane?',
      'Oh, yes, I know the muffin man,',
      'The muffin man, the muffin man,',
      'Oh, yes, I know the muffin man,',
      'Who lives on Drury Lane.',
      'Oh, do you know the muffin man,',
      'The muffin man, the muffin man?',
      'Oh, do you know the muffin man,',
      'Who lives on Drury Lane?',
      'Oh, yes, I know the muffin man,',
      'The muffin man, the muffin man,',
      'Oh, yes, I know the muffin man,',
      'Who lives on Drury Lane.',
    ] },
  { id: 'pat-a-cake', title: 'Pat-a-Cake', emoji: '🍰', audio: '/songs/pat-a-cake.mp3', duration: 144.0, leadIn: 0.72, outro: 143.64, credit: PACK_CREDIT, lines: [
      'Pat-a-cake, pat-a-cake, baker\'s man,',
      'Bake me a cake as fast as you can.',
      'Roll it, and pat it, and mark it with a B,',
      'And put it in the oven for baby and me.',
      'Pat-a-cake, pat-a-cake, baker\'s man,',
      'Bake me a cake as fast as you can.',
      'Roll it, and pat it, and mark it with a B,',
      'And put it in the oven for baby and me.',
      'Pat-a-cake, pat-a-cake, baker\'s man,',
      'Bake me a cake as fast as you can.',
      'Roll it, and pat it, and mark it with a B,',
      'And put it in the oven for baby and me.',
      'Pat-a-cake, pat-a-cake, baker\'s man,',
      'Bake me a cake as fast as you can.',
      'Roll it, and pat it, and mark it with a B,',
      'And put it in the oven for baby and me.',
      'Pat-a-cake, pat-a-cake, baker\'s man,',
      'Bake me a cake as fast as you can.',
      'Roll it, and pat it, and mark it with a B,',
      'And put it in the oven for baby and me.',
      'Pat-a-cake, pat-a-cake, baker\'s man,',
      'Bake me a cake as fast as you can.',
      'Roll it, and pat it, and mark it with a B,',
      'And put it in the oven for baby and me.',
      'Pat-a-cake, pat-a-cake, baker\'s man,',
      'Bake me a cake as fast as you can.',
      'Roll it, and pat it, and mark it with a B,',
      'And put it in the oven for baby and me.',
      'Pat-a-cake, pat-a-cake, baker\'s man,',
      'Bake me a cake as fast as you can.',
      'Roll it, and pat it, and mark it with a B,',
      'And put it in the oven for baby and me.',
    ] },
  { id: 'rain-rain-go-away', title: 'Rain, Rain, Go Away', emoji: '🌧️', audio: '/songs/rain-rain-go-away.mp3', duration: 105.8, leadIn: 0.54, outro: 103.93, credit: PACK_CREDIT, lines: [
      'Rain, rain, go away',
      'Come again another day',
      'Daddy wants to play',
      'Rain, rain go away',
      'Rain, rain, go away',
      'Come again another day',
      'Mommy wants to play',
      'Rain, rain, go away',
      'Rain, rain, go away',
      'Come again another day',
      'Brother wants to play',
      'Rain, rain, go away',
      'Rain, rain, go away',
      'Come again another day',
      'Sister wants to play',
      'Rain, rain, go away',
      'Rain, Rain, go away',
      'Come again another day',
      'Baby wants to play',
      'Rain, rain, go away',
      'Rain, Rain, go away',
      'Come again another day',
      'All the family wants to play',
      'Rain, rain, go away',
    ] },
  { id: 'ring-a-ring-o-roses', title: "Ring a Ring o' Roses", emoji: '🌹', audio: '/songs/ring-a-ring-o-roses.mp3', duration: 94.2, leadIn: 1.11, outro: 89.87, credit: PACK_CREDIT, lines: [
      'Ring-a-ring o\' roses,',
      'A pocket full of posies,',
      'A-tishoo, a-tishoo!',
      'We all fall down.',
    ] },
  { id: 'shes-coming-round-the-mountain', title: "She'll Be Coming Round the Mountain", emoji: '⛰️', audio: '/songs/shes-coming-round-the-mountain.mp3', duration: 189.6, leadIn: 1.61, outro: 187.2, credit: PACK_CREDIT, lines: [
      'She\'ll be coming round the mountain when she comes',
      'She\'ll be coming round the mountain when she comes',
      'She\'ll be coming round the mountain',
      'She\'ll be coming round the mountain',
      'She\'ll be coming round the mountain when she comes.',
      'She\'ll be coming round the mountain when she comes',
      'She\'ll be coming round the mountain when she comes',
      'She\'ll be coming round the mountain',
      'She\'ll be coming round the mountain',
      'She\'ll be coming round the mountain when she comes.',
      'Singing \'ay, ay, yippee, yippee ay!\'',
      'Singing \'ay, ay, yippee, yippee ay!\'',
      'Singing \'ay, ay, yippee, ay, ay, yippee!\'',
      'Singing \'ay, ay, yippee, yippee ay!\'',
      'She\'ll be riding six white horses when she comes',
      'She\'ll be riding six white horses when she comes',
      'She\'ll be riding six white horses',
      'She\'ll be riding six white horses',
      'She\'ll be riding six white horses when she comes.',
      'Singing \'ay, ay, yippee, yippee ay!\'',
      'Singing \'ay, ay, yippee, yippee ay!\'',
      'Singing \'ay, ay, yippee, ay, ay, yippee!\'',
      'Singing \'ay, ay, yippee, yippee ay!\'',
      'Well we\'ll all go out to meet her when she comes',
      'Well we\'ll all go out to meet her when she comes',
      'We\'ll all go out to meet her when she comes',
      'Yes, we\'ll all go out to meet her when she comes',
      'Yes, we\'ll all go out to meet her when she comes.',
      'Singing \'ay, ay, yippee, yippee ay!\'',
      'Singing \'ay, ay, yippee, yippee ay!\'',
      'Singing \'ay, ay, yippee, ay, ay, yippee!\'',
      'Singing \'ay, ay, yippee, yippee ay!\'',
      'She\'ll be wearing silk pyjamas when she comes',
      'She\'ll be wearing silk pyjamas when she comes',
      'She\'ll be wearing pink pyjamas',
      'She\'ll be wearing pink pyjamas',
      'She\'ll be wearing pink pyjamas when she comes.',
      'Singing \'ay, ay, yippee, yippee ay!\'',
      'Singing \'ay, ay, yippee, yippee ay!\'',
      'Singing \'ay, ay, yippee, ay, ay, yippee!\'',
      'Singing \'ay, ay, yippee, yippee ay!\'',
      'She\'ll be coming round the mountain when she comes',
      'She\'ll be coming round the mountain when she comes',
      'She\'ll be coming round the mountain',
      'She\'ll be coming round the mountain',
      'She\'ll be coming round the mountain when she comes.',
    ] },
  { id: 'teddy-bear', title: 'Teddy Bear, Teddy Bear', emoji: '🧸', audio: '/songs/teddy-bear.mp3', duration: 76.9, leadIn: 0.35, outro: 76.16, credit: PACK_CREDIT, lines: [
      'Teddy bear, teddy bear, turn around,',
      'Teddy bear, teddy bear, touch the ground,',
      'Teddy bear, teddy bear, reach up high,',
      'Teddy bear, teddy bear, touch the sky,',
      'Teddy bear, teddy bear, take my hand,',
      'Teddy bear, teddy bear, you\'re my friend,',
      'Teddy bear, teddy bear, I love you,',
      'Teddy bear, teddy bear, this is true,',
      'Teddy bear, teddy bear, turn off the light',
      'Everyone says "shhhhh"',
      'Teddy bear, teddy bear, say goodnight.',
    ] },
  { id: 'ten-in-the-bed', title: 'Ten in the Bed', emoji: '🛏️', audio: '/songs/ten-in-the-bed.mp3', duration: 160.2, leadIn: 0.0, outro: 158.9, credit: PACK_CREDIT, lines: [
      'There were ten in the bed',
      'And the little one said,',
      '"Roll over! Roll over!"',
      'So they all rolled over and',
      'one fell out',
      'There were nine in the bed',
      'And the little one said,',
      '"Roll over! Roll over!"',
      'So they all rolled over',
      'And one fell out',
      'There were eight in the bed',
      'And the little one said,',
      '"Roll over! Roll over!"',
      'So they all rolled over and one fell out',
      'There were seven in the bed',
      'And the little one said,',
      '"Roll over! Roll over!"',
      'So they all rolled over and one fell out',
      'There were six in the bed',
      'And the little one said,',
      '"Roll over! Roll over!"',
      'So they all rolled over and one fell out',
      'There were five in the bed',
      'And the little one said,',
      '"Roll over! Roll over!"',
      'So they all rolled over and one fell out',
      'There were four in the bed',
      'And the little one said,',
      '"Roll over! Roll over!"',
      'So they all rolled over and one fell out',
      'There were three in the bed',
      'And the little one said,',
      '"Roll over! Roll over!"',
      'So they all rolled over and one fell out',
      'There were two in the bed',
      'And the little one said,',
      '"Roll over! Roll over!"',
      'So they all rolled over and one fell out',
      'There was one in the bed',
      'And the little one said,',
      '"Good night"',
    ] },
  { id: 'twinkle', title: 'Twinkle Twinkle Little Star', emoji: '⭐', audio: '/songs/twinkle.mp3', duration: 135.4, leadIn: 1.07, outro: 131.33, credit: PACK_CREDIT, lines: [
      'Twinkle, twinkle, little star,',
      'How I wonder what you are.',
      'Up above the world so high,',
      'Like a diamond in the sky.',
      'Twinkle, twinkle, little star,',
      'How I wonder what you are.',
      'When the blazing sun is gone,',
      'When he nothing shines upon,',
      'Then you show your little light,',
      'Twinkle, twinkle, all the night.',
      'Then the traveler in the dark,',
      'Thanks you for your tiny spark,',
      'He could not see which way to go,',
      'If you did not twinkle so.',
      'In the dark blue sky you keep,',
      'And often through my curtains peep,',
      'For you never shut your eye,',
      'Till the sun is in the sky.',
      'As your bright and tiny spark,',
      'Lights the traveler in the dark.',
      'Though I know not what you are,',
      'Twinkle, twinkle, little star.',
    ] },
  { id: 'wheels-on-the-bus', title: 'Wheels on the Bus', emoji: '🚌', audio: '/songs/wheels-on-the-bus.mp3', duration: 108.4, leadIn: 0.75, outro: 103.54, credit: PACK_CREDIT, lines: [
      'The wheels on the bus go round and round,',
      'Round and round, round and round',
      'The wheels on the bus go round and round,',
      'All through the town',
      'The doors on the bus go open and shut',
      'Open and shut, open and shut',
      'The doors on the bus go open and shut',
      'All through the town',
      'The wipers on the bus go swish swish swish',
      'Swish swish swish, swish swish swish',
      'The wipers on the bus go swish swish swish',
      'All through the town',
      'The baby on the bus goes waa waa waa',
      'Waa waa waa, waa waa waa',
      'The baby on the bus goes waa waa waa',
      'All through the town',
      'The mommy on the bus goes shhh, shhh, shhh',
      'Shh shh shh, shh shh shh',
      'The mommy on the bus goes shhh, shhh, shhh',
      'All through the town',
      'The daddy on the bus goes read read read',
      'Read read read, read read read',
      'The daddy on the bus goes read read read',
      'All through the town',
      'The mommy and the daddy say "I love you,',
      'I love you, I love you"',
      'The mommy and the daddy say "I love you,',
      'All through the town',
    ] },
  { id: 'yankee-doodle', title: 'Yankee Doodle', emoji: '🇺🇸', audio: '/songs/yankee-doodle.mp3', duration: 84.9, leadIn: 0.87, outro: 82.75, credit: PACK_CREDIT, lines: [
      'Yankee Doodle went to town,',
      'A-riding on a pony,',
      'He stuck a feather in his hat,',
      'And called it macaroni.',
      'Yankee Doodle, keep it up,',
      'Yankee Doodle dandy,',
      'Mind the music and the step,',
      'And with the girls be handy.',
      'Yankee Doodle went to town,',
      'A-riding on a pony,',
      'He stuck a feather in his hat,',
      'And called it macaroni.',
      'Yankee Doodle, keep it up,',
      'Yankee Doodle dandy,',
      'Mind the music and the step,',
      'And with the girls be handy.',
    ] },
]
